version: "3.7"

volumes:
  data:

services:
  app:
    build:
      context: ./src
      dockerfile: ./Dockerfile-dev
    env_file: ./src/.env
    environment:
      - ENV=dev
  db:
    image: postgres:12.4-alpine
    env_file: ./src/.env