name: App Build and deploy (dockerhub)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  IMAGE_NAME: akaytatsu/gocusign
  IMAGE_TAG: $(date +%s)
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
#       run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

#     - name: Build and up
#       run: |
#         cp src/.env.sample src/.env
#         docker-compose -f docker-compose.yml -f docker-compose.tests.yml down
#         docker-compose -f docker-compose.yml -f docker-compose.tests.yml build
#         docker-compose -f docker-compose.yml -f docker-compose.tests.yml up -d --no-build

#     - name: Run tests
#       run: docker-compose -f docker-compose.yml -f docker-compose.tests.yml exec -T app go test -v -bench=. ./... -timeout 30m

#     - name: Stop
#       run: docker-compose -f docker-compose.yml -f docker-compose.tests.yml stop
